---

- name: set facts
  set_fact:
    role_comment: "( {{ docker_container_name | default('aem') }} )"
  tags:
    - aem-content

- name: process role with parameters parameters {{ role_comment }}
  debug:
    msg:
      - "aem_port: {{ aem_port }}"
      - "aem_host: {{ aem_host }}"
      - "aem_username: {{ aem_username }}"
      - "aem_password: {{ aem_password }}"
      - "aem_content_action: {{ aem_content_action }}"
      - "aem_content_list: {{ aem_content_list }}"
  tags:
    - always

- name: fail if aem host info is not set {{ role_comment }}
  fail:
    msg: AEM Host, Port, Content Action or Content List not provided
  when:
    - not aem_port
    - not aem_host
    - not aem_username
    - not aem_password
    - not aem_content_action
    - not aem_content_list
  tags:
    - always

- name: set path permissions
  aem_set_permission: >
    host={{ aem_host }}
    port={{ aem_port }}
    user_or_group_name='{{ item.user_or_group_name }}'
    path='{{ item.path }}'
    permissions='{{ item.permissions }}'
    aem_username='{{ aem_username }}'
    aem_password='{{ aem_password }}'
  with_items: "{{ aem_content_list }}"
  when:
    - aem_content_action in aem_content_action_set_permission
  tags:
    - set_permissions

- name: set path property
  aem_set_property: >
    host={{ aem_host }}
    port={{ aem_port }}
    path='{{ item.path }}'
    property_name='{{ item.property_name }}'
    property_value='{{ item.property_value }}'
    aem_username='{{ aem_username }}'
    aem_password='{{ aem_password }}'
  with_items: "{{ aem_content_list }}"
  when:
    - aem_content_action in aem_content_action_set_property
  tags:
    - set_property
