---
- name: Converge
  hosts: instance
  become: true
  vars:
    local_role_name: "ansible-role-aem-content"
    role_name: "{% if lookup('env','ROLE_NAME_FULL') %}{{ lookup('env','ROLE_NAME_FULL') }}{% else %}{{ local_role_name }}{% endif %}"
    test_container_name: "{{ local_role_name }}-test"
    test_aem_port: "{{ service_aem_port }}"
    test_aem_property_url: "/libs/granite/dispatcher/content/vanityUrls.json"
    test_aem_property_content: "test-value"

  pre_tasks:
    - name: get docker host ip
      become: true
      shell: |
        set -o pipefail
        /sbin/ip route | awk '/default/ { print $3 }'
      args:
        executable: /bin/bash
      register: dockerhost_ip
      changed_when: false

  tasks:
    - name: set aem license
      include_role:
        name: "aem_design.aem_license"
      vars:
        aem_license_key: "{{ service_aem_license_key }}"
        aem_license_name: "{{ service_aem_license_name }}"
        aem_port: "{{ test_aem_port }}"
        aem_host: "{{ dockerhost_ip.stdout }}"
        debug_hide: false
    - name: verify aem is ready
      include_role:
        name: "aem_design.aem_verify"
      vars:
        aem_port: "{{ test_aem_port }}"
        aem_host: "{{ dockerhost_ip.stdout }}"
        debug_hide: false
    - name: set permissions
      include_role:
        name: "{{ role_name }}"
      vars:
        aem_port: "{{ test_aem_port }}"
        aem_host: "{{ dockerhost_ip.stdout }}"
        aem_content_action: "set_permission"
        aem_content_list: [
          {
            user_or_group_name: 'everyone',
            path: '/libs/granite/dispatcher/content/vanityUrls',
            permissions: 'read:true'
          }
        ]
        debug_hide: false
    - name: set property
      include_role:
        name: "{{ role_name }}"
      vars:
        aem_port: "{{ test_aem_port }}"
        aem_host: "{{ dockerhost_ip.stdout }}"
        aem_content_action: "set_property"
        aem_content_list: [
          {
            path: '/libs/granite/dispatcher/content/vanityUrls',
            property_name: 'test',
            property_value: "{{ test_aem_property_content }}"
          }
        ]
        debug_hide: false

  post_tasks:
    - name: check property content {{ role_comment }}
      uri:
        url: "http://{{ dockerhost_ip.stdout }}:{{ test_aem_port }}{{ test_aem_property_url }}"
        follow_redirects: "all"
        return_content: true
        timeout: 300
      register: aem_page
      until: test_aem_property_content in aem_page.content
      delay: "{{ wait_delay | default(5) }}"
      retries: 360
